apiVersion: v1
kind: Service
metadata:
  name: redis-managerment
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
    nodePort: 32702
  
