apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-2
spec:
  containers:
  - name: test-container-2
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
      - name: SPECIAL_LEVEl_KEY
        valueFrom:
          configMapKeyRef:
            name: special-config
            key: special.how
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: env-config
            key: log_level
  restartPolicy: Never
