apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-3
spec:
  containers:
  - name: test-container-3
    image: k8s.gcr.io/busybox
    command: [ "/bin/sh", "-c", "env" ]
    envFrom:
    - configMapRef:
        name: special-config
  restartPolicy: Never 
