apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: r00tm1
      volumeMounts:
      - name: config-volume
        mountPath: /etc/mysql/conf.d/mysql-user.cnf
        subPath: mysql-user.cnf
  volumes:
    - name: config-volume
      configMap:
        name: mysql-config
  restartPolicy: Never
