apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-managerment
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
    nodePort: 32705
  
