apiVersion: v1
kind: Service
metadata:
  name: mariadb-managerment
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
  - port: 3306 
    protocol: TCP
    targetPort: 3306
    nodePort: 32701
  
