apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec: 
  serviceName: "mariadb"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.1
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1qazxsw2
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: timezone
          mountPath: /etc/localtime
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "rbd"
        resources:
          requests:
            storage: 50Gi
#Accessing the MySQL instance
#kubectl run -it --rm --image=mysql:5.6 --restart=Never mysql-client -- mysql -h mariadb -p1qazxsw2
