apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-use-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 30Gi
