#Burstable
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-2
  namespace: default
spec:
  containers:
  - name: qos-demo-2-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi" #not same requests
      requests:
        memory: "100Mi"
