apiVersion: apps/v1
kind: Deployment
metadata:
  name: dubboadmin
  labels:
    app: dubboadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dubboadmin
  template:
    metadata:
      labels:
        app: dubboadmin
    spec:
      containers:
      - name: dubboadmin
        image: registry.cn-hangzhou.aliyuncs.com/ameizi/dubbo-admin:2.5.4
        env:
        - name: ROOT_PASSWORD
          value: root
        - name: GUEST_PASSWORD
          value: guest
        - name: ZK
          value: zookeeper:2181
        resources:
          limits:
            memory: "2048Mi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dubboadmin
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 32008
    targetPort: 8080
  selector:
    app: dubboadmin
