apiVersion: v1
kind: Service
metadata:
  name: zookeeper-managerment
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    nodePort: 32703
  
