apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
type: "kubernetes.io/rbd"
data:
  key: QVFCTVJVUmJlaGlaRUJBQXUwV0hMemN6am5zOFpvMlVZSmFpTmc9PQ==

---
#ceph-storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
provisioner: ceph.com/rbd
parameters:
  monitors: 192.168.100.247:6789
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: default
  pool: k8s
  userId: admin
  userSecretName: ceph-secret-admin
  fsType: xfs
  imageFormat: "2"
  imageFeatures: "layering"

---
# mariadb-pvc-use-rbd.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb1-use-storageclass
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 30Gi

---
# mariadb-deployment-stateful.yaml
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.1
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 1qazxsw2
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: pvc-mariadb-use-storageclass
