apiVersion: v1
kind: Service
metadata:
  name: mongodb-managerment
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32704
  
